services:
  - type: web
    name: leaderboard-dashboard
    runtime: python3
    buildCommand: |
      if ! command -v psql &> /dev/null; then
        echo "Error: psql is not installed. Please contact Render support."
        exit 1
      fi
      psql $DATABASE_URL -f schema.sql || echo "PostgreSQL initialization failed. Ensure schema.sql is valid."
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://username:password@localhost:5432/leaderboard
    plan: free
    autoDeploy: true