services:
  - type: web
    name: leaderboard-dashboard
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    autoDeploy: true